baseURL = "https://from-stata-to-r.netlify.com"
title = "From Stata to R"
copyright = "Copyright © 2018, Etienne Bacher. Built with Blogdown. Powered by indigo theme for Hugo"
languageCode = "en-US"
theme = "indigo"
paginate = 20
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

disqusShortname = "indigo"

[params]
  Author = "Etienne Bacher"
  Description = "A blog to narrate my transition from Stata to R"
  Subtitle = ""
  Avatar = "images/site-logo.svg"
  Biography = "I'm a French student in Economics, currently finishing my Master's degree."
  ShowBio = true
  PermalinkText = "🔗"
  mainSections = ["posts", "updates"]
  disableDisqusTypes = ["page"]

  comments = true
  # Contact/social-network identifiers for social icons
  EmailAddress = "etienne.bacher@orange.fr"
  GitHubUser = "etiennebacher"
  LinkedInUser = "Etienne Bacher"
  StackOverflowUser = "bretauv"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "etienne.bacher@orange.fr" 
    GitHubUser = "etiennebacher"
    Country = "France"
    City = "Clermont-Ferrand"
    
  [params.endpoints]
    Auth = "https://indieauth.com/auth"
    Token = "https://tokens.indieauth.com/token"
    # To get webmention support, just register at webmention.io and paste the link for endpoint here.
    #Webmention = "https://webmention.io/<yourusername>/webmention"
    # To get micropub support, you'll need to install a Micropub endpoint at your site and put its link there.
    # To get an endpoint with Hugo support, use nanopub: https://github.com/dg01d/nanopub
    # It will probably require some PHP hackery though, as it's fairly basic.
    #Micropub = ""
    # To get microsub support, you can use Aperture from p3k. Either go to https://aperture.p3k.io or self-host it (it's open source!)
    #Microsub = ""
    
[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5